
server:
  port: 8088
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    connection-timeout: 10000
    template:
      mandatory: true
    publisher-confirms: true #消息确认